# ========= MOSARIYA Netlify config =========
[build]
  publish = "."

# ---------- Canonical, HTTPS, www ----------
[[redirects]]
  from = "http://mosariya.uz/*"
  to   = "https://www.mosariya.uz/:splat"
  status = 301
  force  = true

[[redirects]]
  from = "https://mosariya.uz/*"
  to   = "https://www.mosariya.uz/:splat"
  status = 301
  force  = true

# ---------- Trailing slash normalization (keep slashless) ----------
[[redirects]]
  from = "/:page/"
  to   = "/:page"
  status = 301
  force  = true
  conditions = {Country = ["*"]}

# ---------- Cache headers ----------
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/styles.css"
  [headers.values]
    Cache-Control = "public, max-age=604800"

[[headers]]
  for = "/script.js"
  [headers.values]
    Cache-Control = "public, max-age=604800"
