# ========= MOSARIYA Netlify config =========
[build]
  publish = "."

# ---------- Canonical, HTTPS, www ----------
[[redirects]]
  from = "http://mosariya.uz/*"
  to   = "https://www.mosariya.uz/:splat"
  status = 301
  force  = true

[[redirects]]
  from = "https://mosariya.uz/*"
  to   = "https://www.mosariya.uz/:splat"
  status = 301
  force  = true

# ---------- Trailing slash normalization (keep slashless) ----------
[[redirects]]
  from = "/:page/"
  to   = "/:page"
  status = 301
  force  = true
  conditions = {Country = ["*"]}

# ---------- Default 404 ----------
# Netlify сам отдаёт /404.html как кастомную страницу, отдельный редирект не обязателен.

# ---------- Cache headers ----------
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/styles.css"
  [headers.values]
    Cache-Control = "public, max-age=604800"

[[headers]]
  for = "/script.js"
  [headers.values]
    Cache-Control = "public, max-age=604800"

# ---------- Security headers ----------
[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "SAMEORIGIN"
    Referrer-Policy = "no-referrer-when-downgrade"
    X-XSS-Protection = "0"
    Permissions-Policy = "geolocation=(), camera=(), microphone=()"
